project_id = "skfliyjipemazvyxcxtm"

[functions.send-lead-reminders]
verify_jwt = true

[functions.get-mapbox-token]
verify_jwt = true

[functions.client-ai-summary]
verify_jwt = true

[functions.salesperson-ai-summary]
verify_jwt = true

[functions.send-offer-email]
verify_jwt = true

[functions.send-contract-email]
verify_jwt = true

[functions.send-scheduled-reports]
verify_jwt = true
